- job:
    name: mcom03-flash-tools-build-docs
    parent: build-docs
    vars:
      tox_envlist: docs
      build_items:
        - title: mcom03-flash-tools doc
          basename: mcom03-flash-tools-docs
          build_dir: docs/build/html

- project:
    check:
      jobs: &check-jobs
        - mcom03-flash-tools-build-docs:
            irrelevant-files:
              - \.
        - mcom03-linux-fast-tests:
            files: &observed_files
              - mcom03_flash_tools/
              - pyproject.toml$
        - mcom03-linux66-bootromqspi0-fast-tests:
            files: *observed_files
        - mcom03-tests-tox:
            files: *observed_files
        - ecam-fct-tox:
            files: *observed_files
        - tox
    gate:
      jobs: *check-jobs
    post: &publish-jobs
      jobs:
        - mcom03-flash-tools-build-docs
        - mcom03-flash-tools-publish-docs
    tag: *publish-jobs
