- project:
    check:
      jobs:
        - mcom03-linux-fast-tests:
            files: &observered_files
              - .*\.py$
              - mcom03_flash_tools/.*
        - mcom03-linux-priv-tl-fast-tests:
            files: *observered_files
        - tox
