[tox]
env_list =
  doctest
  {py39,py312}-mypy
  {py39,py312}-pylint
  pre-commit

[base]
basepython =
  py39: python3.9
  py312: python3.12

[testenv]
basepython = python3.12
allowlist_externals = bash

[testenv:doctest]
commands =
  python -m doctest -v mcom03_flash_tools/mcom03_flash.py
  python -m doctest -v mcom03_flash_tools/mcom03_otp.py

[testenv:{py39,py312}-mypy]
basepython = {[base]basepython}
deps =
  mypy<=0.910
commands = bash -c "mypy --ignore-missing-imports --check-untyped-defs $(git ls-files '*.py')"

[testenv:{py39,py312}-pylint]
basepython = {[base]basepython}
deps = pylint<4.1
commands = pylint -E mcom03_flash_tools

[testenv:pre-commit]
skip_install = true
deps = pre-commit==2.20
commands = pre-commit run --all-files
